### ISSUE TITLE
Add new model INF-ORM-Llama3.1-70B

### ISSUE THREAD

**Issue by Mghao** [allenai/reward-bench#207]
We trained a new model called "INF-ORM-Llama3.1-70B".
https://huggingface.co/infly/INF-ORM-Llama3.1-70B

**Comment by 1Teng** [comment]
Hello, I'm a research assist in Tsinghua Shenzhen International Graduated School, we evaluated the reward model using the same instructions on 8*A100 GPUs. However, the results are not the same as you say, and even the two adjacent experiments reflect large differences.
Here are the results we got from one of the runs:
{'Chat': 0.6759776536312849, 'Chat Hard': 0.8771929824561403, 'Safety': 0.9162162162162162, 'Reasoning': 0.9216456594096143}  
I'm wondering the reason for this phenomenon, is it because of temperature or random seeds?
Looking forward to your reply, thanks!
